-- EXPLAIN ANALYZE ДО 

"Limit  (cost=15.62..15.65 rows=1 width=122) (actual time=0.188..0.190 rows=0 loops=1)"
"  ->  Unique  (cost=15.62..15.65 rows=1 width=122) (actual time=0.187..0.189 rows=0 loops=1)"
"        ->  Sort  (cost=15.62..15.62 rows=1 width=122) (actual time=0.187..0.189 rows=0 loops=1)"
"              Sort Key: (count(r.rental_id)) DESC, (max(r.return_date)) DESC, c.customer_id, c.first_name, c.last_name, c.email, c.registration_date, (COALESCE(sum(CASE WHEN (r.return_date IS NULL) THEN 1 ELSE 0 END), '0'::bigint)), ((SubPlan 1)), ((SubPlan 2)), ((SubPlan 3)), (sum(CASE WHEN ((m.genre)::text = 'Action'::text) THEN 1 ELSE 0 END))"
"              Sort Method: quicksort  Memory: 25kB"
"              ->  GroupAggregate  (cost=6.42..15.61 rows=1 width=122) (actual time=0.161..0.163 rows=0 loops=1)"
"                    Group Key: c.customer_id"
"                    Filter: (count(r.rental_id) > 10)"
"                    Rows Removed by Filter: 30"
"                    ->  Sort  (cost=6.42..6.43 rows=1 width=272) (actual time=0.140..0.143 rows=30 loops=1)"
"                          Sort Key: c.customer_id"
"                          Sort Method: quicksort  Memory: 27kB"
"                          ->  Hash Join  (cost=3.90..6.41 rows=1 width=272) (actual time=0.100..0.122 rows=30 loops=1)"
"                                Hash Cond: (c.customer_id = r.customer_id)"
"                                ->  Seq Scan on customers c  (cost=0.00..2.39 rows=31 width=46) (actual time=0.007..0.022 rows=31 loops=1)"
"                                      Filter: (registration_date <= '2022-12-31'::date)"
"                                ->  Hash  (cost=3.88..3.88 rows=1 width=230) (actual time=0.076..0.077 rows=30 loops=1)"
"                                      Buckets: 1024  Batches: 1  Memory Usage: 10kB"
"                                      ->  Hash Join  (cost=1.46..3.88 rows=1 width=230) (actual time=0.047..0.057 rows=30 loops=1)"
"                                            Hash Cond: (m.movie_id = r.movie_id)"
"                                            ->  Seq Scan on movies m  (cost=0.00..2.30 rows=30 width=222) (actual time=0.005..0.008 rows=30 loops=1)"
"                                            ->  Hash  (cost=1.45..1.45 rows=1 width=16) (actual time=0.026..0.026 rows=30 loops=1)"
"                                                  Buckets: 1024  Batches: 1  Memory Usage: 10kB"
"                                                  ->  Seq Scan on rentals r  (cost=0.00..1.45 rows=1 width=16) (actual time=0.003..0.007 rows=30 loops=1)"
"                                                        Filter: ((rental_date >= '2020-01-01'::date) AND (rental_date <= '2022-12-31'::date))"
"                    SubPlan 1"
"                      ->  Aggregate  (cost=3.78..3.79 rows=1 width=8) (never executed)"
"                            ->  Sort  (cost=3.77..3.78 rows=1 width=4) (never executed)"
"                                  Sort Key: m_1.movie_id"
"                                  ->  Nested Loop  (cost=0.00..3.76 rows=1 width=4) (never executed)"
"                                        Join Filter: (m_1.movie_id = r2.movie_id)"
"                                        ->  Seq Scan on movies m_1  (cost=0.00..2.38 rows=1 width=4) (never executed)"
"                                              Filter: ((genre)::text = 'Drama'::text)"
"                                        ->  Seq Scan on rentals r2  (cost=0.00..1.38 rows=1 width=4) (never executed)"
"                                              Filter: (customer_id = c.customer_id)"
"                    SubPlan 2"
"                      ->  Aggregate  (cost=3.81..3.82 rows=1 width=32) (never executed)"
"                            ->  Hash Join  (cost=1.39..3.81 rows=1 width=12) (never executed)"
"                                  Hash Cond: (m2.movie_id = r3.movie_id)"
"                                  ->  Seq Scan on movies m2  (cost=0.00..2.30 rows=30 width=16) (never executed)"
"                                  ->  Hash  (cost=1.38..1.38 rows=1 width=4) (never executed)"
"                                        ->  Seq Scan on rentals r3  (cost=0.00..1.38 rows=1 width=4) (never executed)"
"                                              Filter: (customer_id = c.customer_id)"
"                    SubPlan 3"
"                      ->  Aggregate  (cost=1.53..1.54 rows=1 width=8) (never executed)"
"                            ->  Seq Scan on rentals r4  (cost=0.00..1.52 rows=1 width=4) (never executed)"
"                                  Filter: ((rental_date >= '2021-01-01'::date) AND (rental_date <= '2022-12-31'::date) AND (customer_id = c.customer_id))"
"Planning Time: 1.311 ms"
"Execution Time: 0.356 ms"


-- EXPLAIN ANALYZE ПОСЛЕ 

